library(jsonlite)
library(magrittr)

source("R/model_component_helpers.R")

## /////////////////////////////////////////////////////////////////////////////
## READ FROM REMOTE CMIP6 CONTROLLED VOCABULARY
## /////////////////////////////////////////////////////////////////////////////

## CMIP6 Institutions
url <- "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/main/CMIP6_institution_id.json"

## List of all institutions
inst.list <- fromJSON(url) %>% extract2("institution_id")
insts <- names(inst.list)

## /////////////////////////////////////////////////////////////////////////////
## CREATE OWL FILE
## /////////////////////////////////////////////////////////////////////////////

## OWL template file (contains header and imports)
## Use 'restart.owl()' to start from blank template
## The template already contains the OWL header with relevant imports and metadata
## Please check the 'datasource' ontology version dependency

owl.file <- "CMIP6-institutions.owl"
restart.owl(voc = "institutions")

# Open file in add mode
con <- file(owl.file, open = "a")

## VOC URI
voc <- "https://raw.githubusercontent.com/metaclip/CMIP6/devel/CMIP6-institutions.owl"

cat("\t<!--\n", file = con, append = TRUE) 
cat("\t///////////////////////////////////////////////////////////////////////////////////////\n",
    file = con, append = TRUE)
cat("\t//\n", file = con, append = TRUE)
cat("\t// Individuals\n", file = con, append = TRUE)
cat("\t//\n", file = con, append = TRUE)
cat("\t///////////////////////////////////////////////////////////////////////////////////////\n",
    file = con, append = TRUE)
cat("\t-->\n\n", file = con, append = TRUE)

for (i in 1:length(insts)) {
    
    inst <- insts[[i]]
    desc <- inst.list[[inst]]
    # NamedIndividual instance:
    instance <- paste0(voc, "#", inst)
    
    cat("\t<!--\n", file = con, append = TRUE)
    cat("\t\t", instance, "\n", file = con, append = TRUE)
    cat("\t-->\n", file = con, append = TRUE)
    
    ## Write Institution individual and class ----------------------------------
    ## By default, Modelling centers are also encoded as data providers
    
    cat("\n", file = con, append = TRUE)
    cat("\t<owl:NamedIndividual rdf:about=\"", instance, "\">",
        sep = "", file = con, append = TRUE)
    cat("\n", file = con, append = TRUE)
    cat("\t\t<rdf:type rdf:resource=\"http://www.metaclip.org/datasource/datasource.owl#ModellingCenter\"/>\n",
        file = con, append = TRUE)
    cat("\t\t<rdf:type rdf:resource=\"http://www.metaclip.org/datasource/datasource.owl#DataProvider\"/>",
        file = con, append = TRUE)
    cat("\n", file = con, append = TRUE)
    
    ## Additional properties:
    ## GCM label
    cat("\t\t<rdfs:label>", inst, "</rdfs:label>", sep = "",
        file = con, append = TRUE)
    cat("\n", file = con, append = TRUE)
    ## GCM long name
    cat("\t\t<dc:description xml:lang=\"en\">", desc,
        "</dc:description>", sep = "", file = con, append = TRUE)
    cat("\n", file = con, append = TRUE)
    cat("\t</owl:NamedIndividual>\n", file = con, append = TRUE)
    cat("\n", file = con, append = TRUE)
}

cat("</rdf:RDF>\n\n", sep = "", file = con, append = TRUE)

cat("<!-- ", file = con, append = TRUE)
cat("Automatically generated by '1_import_CMIP6_institutions.R' on", as.character(Sys.Date()),
    "using", gsub("\\(.*", "", R.version.string),
    "<https://github.com/METACLIP/CMIP6>", file = con, append = TRUE)
cat(" -->\n", file = con, append = TRUE)
## Close connection 
close(con)
